export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  CASE_MANAGER: "CASE_MANAGER",
  TEAM_LEAD: "TEAM_LEAD",
  MANAGER: "MANAGER",
  FINANCE_HEAD: "FINANCE_HEAD",
};

export const ROLE_LABELS = {
  [ROLES.SUPER_ADMIN]: "Super Admin",
  [ROLES.CASE_MANAGER]: "Case Manager",
  [ROLES.TEAM_LEAD]: "Team Lead",
  [ROLES.MANAGER]: "Manager",
  [ROLES.FINANCE_HEAD]: "Finance Head",
};

export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",   
  VIEW_SYSTEM_ANALYTICS: "VIEW_SYSTEM_ANALYTICS",
  MANAGE_USERS: "MANAGE_USERS",
  DELETE_USERS: "DELETE_USERS",
  DEACTIVATE_USERS: "DEACTIVATE_USERS",
  RESTORE_USERS: "RESTORE_USERS",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  VIEW_VENDORS: "VIEW_VENDORS",
  MANAGE_VENDORS: "MANAGE_VENDORS",
  REVIEW_VENDORS: "REVIEW_VENDORS",
  VIEW_PURCHASE_ORDERS: "VIEW_PURCHASE_ORDERS",
  MANAGE_PURCHASE_ORDERS: "MANAGE_PURCHASE_ORDERS",
  DOWNLOAD_PURCHASE_ORDER: "DOWNLOAD_PURCHASE_ORDER",
  VIEW_INVOICES: "VIEW_INVOICES",
  MANAGE_INVOICES: "MANAGE_INVOICES",
  SUBMIT_INVOICES: "SUBMIT_INVOICES",
  DOWNLOAD_INVOICE: "DOWNLOAD_INVOICE",
  APPROVE_INVOICE_L1: "APPROVE_INVOICE_L1",
  APPROVE_INVOICE_L2: "APPROVE_INVOICE_L2",
  APPROVE_INVOICE_FINAL: "APPROVE_INVOICE_FINAL",
  VIEW_THREE_WAY_MATCHING: "VIEW_THREE_WAY_MATCHING",
  RUN_THREE_WAY_MATCHING: "RUN_THREE_WAY_MATCHING",
  REVIEW_THREE_WAY_MATCHING: "REVIEW_THREE_WAY_MATCHING",
  VIEW_PAYMENTS: "VIEW_PAYMENTS",
  CREATE_PAYMENT_REQUEST: "CREATE_PAYMENT_REQUEST",
  EXECUTE_PAYMENT: "EXECUTE_PAYMENT",
  VIEW_APPROVALS: "VIEW_APPROVALS",
  VIEW_REPORTS: "VIEW_REPORTS",
  VIEW_NOTIFICATIONS: "VIEW_NOTIFICATIONS",

  // Super Admin Report Permissions
  VIEW_VENDOR_REPORTS:    "VIEW_VENDOR_REPORTS",
  EXPORT_VENDOR_REPORTS:  "EXPORT_VENDOR_REPORTS",
  VIEW_PO_REPORTS:        "VIEW_PO_REPORTS",
  EXPORT_PO_REPORTS:      "EXPORT_PO_REPORTS",
  VIEW_INVOICE_REPORTS:   "VIEW_INVOICE_REPORTS",
  EXPORT_INVOICE_REPORTS: "EXPORT_INVOICE_REPORTS",
  VIEW_PAYMENT_REPORTS:   "VIEW_PAYMENT_REPORTS",
  EXPORT_PAYMENT_REPORTS: "EXPORT_PAYMENT_REPORTS",
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_SYSTEM_ANALYTICS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.DEACTIVATE_USERS,
    PERMISSIONS.RESTORE_USERS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_PURCHASE_ORDERS,
    PERMISSIONS.DOWNLOAD_PURCHASE_ORDER,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.DOWNLOAD_INVOICE,
    PERMISSIONS.VIEW_THREE_WAY_MATCHING,
    PERMISSIONS.RUN_THREE_WAY_MATCHING,
    PERMISSIONS.REVIEW_THREE_WAY_MATCHING,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_VENDOR_REPORTS,
    PERMISSIONS.EXPORT_VENDOR_REPORTS,
    PERMISSIONS.VIEW_PO_REPORTS,
    PERMISSIONS.EXPORT_PO_REPORTS,
    PERMISSIONS.VIEW_INVOICE_REPORTS,
    PERMISSIONS.EXPORT_INVOICE_REPORTS,
    PERMISSIONS.VIEW_PAYMENT_REPORTS,
    PERMISSIONS.EXPORT_PAYMENT_REPORTS,
    PERMISSIONS.VIEW_APPROVALS,
  ],
  [ROLES.CASE_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_VENDORS,
    PERMISSIONS.MANAGE_VENDORS,
    PERMISSIONS.VIEW_PURCHASE_ORDERS,
    PERMISSIONS.MANAGE_PURCHASE_ORDERS,
    PERMISSIONS.DOWNLOAD_PURCHASE_ORDER,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.MANAGE_INVOICES,
    PERMISSIONS.SUBMIT_INVOICES,
    PERMISSIONS.DOWNLOAD_INVOICE,
    PERMISSIONS.VIEW_THREE_WAY_MATCHING,
    PERMISSIONS.RUN_THREE_WAY_MATCHING,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.CREATE_PAYMENT_REQUEST,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
  [ROLES.TEAM_LEAD]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_APPROVALS,
    PERMISSIONS.VIEW_PURCHASE_ORDERS,
    PERMISSIONS.DOWNLOAD_PURCHASE_ORDER,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.DOWNLOAD_INVOICE,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.EXECUTE_PAYMENT,
    PERMISSIONS.APPROVE_INVOICE_L1,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_APPROVALS,
    PERMISSIONS.VIEW_PURCHASE_ORDERS,
    PERMISSIONS.DOWNLOAD_PURCHASE_ORDER,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.DOWNLOAD_INVOICE,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.EXECUTE_PAYMENT,
    PERMISSIONS.APPROVE_INVOICE_L2,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
  ],
  [ROLES.FINANCE_HEAD]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_APPROVALS,
    PERMISSIONS.VIEW_VENDORS,
    PERMISSIONS.REVIEW_VENDORS,
    PERMISSIONS.VIEW_PURCHASE_ORDERS,
    PERMISSIONS.DOWNLOAD_PURCHASE_ORDER,
    PERMISSIONS.DOWNLOAD_INVOICE,
    PERMISSIONS.VIEW_THREE_WAY_MATCHING,
    PERMISSIONS.REVIEW_THREE_WAY_MATCHING,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.CREATE_PAYMENT_REQUEST,
    PERMISSIONS.EXECUTE_PAYMENT,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.DEACTIVATE_USERS,
    PERMISSIONS.RESTORE_USERS,
  ],
};

export const permissionsForUser = (user) => (
  user?.permissions?.length ? user.permissions : ROLE_PERMISSIONS[user?.role] || []
);

export const ROUTE_PERMISSIONS = {
  "/dashboard": PERMISSIONS.VIEW_DASHBOARD,
  "/vendors": PERMISSIONS.VIEW_VENDORS,
  "/finance-head/vendors": PERMISSIONS.REVIEW_VENDORS,
  "/purchase-orders": PERMISSIONS.VIEW_PURCHASE_ORDERS,
  "/invoices": PERMISSIONS.VIEW_INVOICES,
  "/three-way-matching": PERMISSIONS.VIEW_THREE_WAY_MATCHING,
  "/receipt-documents": PERMISSIONS.VIEW_THREE_WAY_MATCHING,
  "/payments": PERMISSIONS.VIEW_PAYMENTS,
  "/payment-history": PERMISSIONS.VIEW_PAYMENTS,
  "/approvals": PERMISSIONS.VIEW_APPROVALS,
  "/reports": PERMISSIONS.VIEW_REPORTS,
  "/notifications": PERMISSIONS.VIEW_NOTIFICATIONS,
  "/users": PERMISSIONS.MANAGE_USERS,
  "/super-admin/reports":         PERMISSIONS.VIEW_VENDOR_REPORTS,
  "/super-admin/reports/vendors": PERMISSIONS.VIEW_VENDOR_REPORTS,
  "/super-admin/reports/purchase-orders": PERMISSIONS.VIEW_PO_REPORTS,
  "/super-admin/reports/invoices":        PERMISSIONS.VIEW_INVOICE_REPORTS,
  "/super-admin/reports/payments":        PERMISSIONS.VIEW_PAYMENT_REPORTS,
  "/audit-logs":                          PERMISSIONS.VIEW_AUDIT_LOGS,
  "/finance-head/audit-logs":             PERMISSIONS.VIEW_AUDIT_LOGS,
  "/super-admin/audit-logs":              PERMISSIONS.VIEW_AUDIT_LOGS,
};

export const hasPermission = (user, permission) =>
  Boolean(permissionsForUser(user).includes(permission));

export const canDownloadDocument = (user) => {
  if (!user || !user.role) return false;
  const allowedRoles = [
    ROLES.CASE_MANAGER,
    ROLES.TEAM_LEAD,
    ROLES.MANAGER,
    ROLES.FINANCE_HEAD,
    ROLES.SUPER_ADMIN,
  ];
  return allowedRoles.includes(user.role);
};

export const canAccessPath = (user, pathname) => {
  const matchedRoute = Object.keys(ROUTE_PERMISSIONS)
    .sort((a, b) => b.length - a.length)
    .find((route) => pathname.startsWith(route));

  if (!matchedRoute) return true;
  return hasPermission(user, ROUTE_PERMISSIONS[matchedRoute]);
};
